-- CREATE TABLE "sessions" (
-- 	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
-- 	"user_id" uuid NOT NULL,
-- 	"token" text NOT NULL,
-- 	"ip_address" text,
-- 	"user_agent" text,
-- 	"expires_at" timestamp with time zone NOT NULL,
-- 	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
-- 	CONSTRAINT "sessions_token_unique" UNIQUE("token")
-- );
-- --> statement-breakpoint
-- ALTER TABLE "session" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
-- DROP TABLE "session" CASCADE;--> statement-breakpoint
-- ALTER TABLE "users" ALTER COLUMN "email_verified" SET DATA TYPE boolean;--> statement-breakpoint
-- ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;